import type { Product, Category, HomePageCategory } from './types';

const homePageCategories: HomePageCategory[] = [
    { id: 'decor', name: 'Home & Decor', image: '/decor.png' },
    { id: 'roofing', name: 'Roofing & Fencing', image: '/roof 2.png' },
    { id: 'lighting-electrical', name: 'Lighting & Electrical', image: '/electric cable.png' },
    { id: 'home-decor-2', name: 'Home & Decor', image: '/decor lighting design.png' },
    { id: 'roofing-2', name: 'Roofing & Fencing', image: '/roof 2.png' },
    { id: 'home-decor-3', name: 'Home & Decor', image: '/floor tiles.png' },
    { id: 'lighting-2', name: 'Lighting & Electrical', image: '/artistic lights.png' }
];

const featuredProducts: Product[] = [
  {
    id: 'ample-light',
    name: 'Ample Light',
    price: 2500.00,
    images: ['/Ample Light.png'],
    description: 'A beautiful and bright ample light.',
    longDescription: 'A beautiful and bright ample light, perfect for any room in your house.',
    category: 'lighting-electrical',
    rating: 4.5,
    reviews: 10,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'oval-toilet',
    name: 'Oval Toilet',
    price: 7500.00,
    images: ['/Oval Toilet.png'],
    description: 'A modern and efficient oval toilet.',
    longDescription: 'A modern and efficient oval toilet that saves water and adds a touch of class to your bathroom.',
    category: 'plumbing',
    rating: 4.8,
    reviews: 25,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'sink-cabinet',
    name: 'Whole complete sink and cabinet',
    price: 7000.00,
    images: ['/Whole complete sink and cabinet.png'],
    description: 'A complete sink and cabinet set.',
    longDescription: 'A complete sink and cabinet set, ready to install. Provides ample storage and a sleek look.',
    category: 'plumbing',
    rating: 4.7,
    reviews: 18,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'solar-heater',
    name: 'Solar Heater non-pressurized',
    price: 12000.00,
    images: ['/Solar Heater non-pressurized.png'],
    description: 'An energy-efficient solar water heater.',
    longDescription: 'An energy-efficient non-pressurized solar water heater, perfect for reducing your electricity bills.',
    category: 'plumbing',
    rating: 4.9,
    reviews: 32,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'artistic-lights',
    name: 'Artistic Lights',
    price: 3300.00,
    images: ['/Artistic Lights.png'],
    description: 'Unique and stylish artistic lights.',
    longDescription: 'A collection of unique and stylish artistic lights to make a statement in any room.',
    category: 'lighting-electrical',
    rating: 4.6,
    reviews: 15,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'electric-cable',
    name: 'Electric cable',
    price: 3000.00,
    images: ['/electric cable.png'],
    description: 'High-quality electric wiring cable.',
    longDescription: 'High-quality and durable electric wiring cable, available in various gauges for your needs.',
    category: 'lighting-electrical',
    rating: 4.9,
    reviews: 50,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'wall-bracket',
    name: 'Warm light wall bracket',
    price: 1900.00,
    images: ['/Warm light wall bracket.png'],
    description: 'An elegant warm light wall bracket.',
    longDescription: 'An elegant warm light wall bracket that provides a cozy and inviting ambiance.',
    category: 'lighting-electrical',
    rating: 4.5,
    reviews: 22,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'ppr-fittings',
    name: 'PPR Pipe Fittings',
    price: 30.00,
    images: ['/PPR Pipe Fittings.png'],
    description: 'A set of durable PPR pipe fittings.',
    longDescription: 'A complete set of durable PPR pipe fittings for all your plumbing projects.',
    category: 'plumbing',
    rating: 5.0,
    reviews: 110,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
];

const tankProducts: Product[] = [
  {
    id: 'kentank-2000l',
    name: 'Kentank 2000L',
    price: 15000.00,
    images: ['/kentank 2000l.png'],
    description: 'A durable 2000L Kentank water tank.',
    longDescription: 'A durable 2000L Kentank water tank, ideal for domestic water storage. Made from high-quality food-grade material.',
    category: 'tanks',
    rating: 4.7,
    reviews: 45,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'kentank-3000l',
    name: 'Kentank 3000L',
    price: 10000.00,
    images: ['/kentanks 3000L.png'],
    description: 'A large 3000L Kentank water tank.',
    longDescription: 'A large 3000L Kentank water tank, perfect for residential or commercial use. UV-stabilized for long life.',
    category: 'tanks',
    rating: 4.8,
    reviews: 30,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'cuboid-tank',
    name: 'Water Tank',
    price: 6500.00,
    images: ['/cuboidTank.PNG'],
    description: 'A space-saving cuboid water tank.',
    longDescription: 'A space-saving cuboid water tank, designed for areas with limited space. Easy to install and maintain.',
    category: 'tanks',
    rating: 4.5,
    reviews: 20,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'septic-tank',
    name: 'Septic Tank',
    price: 20000.00,
    images: ['/septic Tank.png'],
    description: 'A reliable and robust septic tank.',
    longDescription: 'A reliable and robust septic tank for effective wastewater management. Built to last with high-strength materials.',
    category: 'tanks',
    rating: 4.9,
    reviews: 55,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'plastic-reservoir-tank',
    name: 'Reservoir Tank',
    price: 5000.00,
    images: ['/plastic-tank.png'],
    description: 'A versatile plastic reservoir tank.',
    longDescription: 'A versatile plastic reservoir tank for various water storage needs. Lightweight and corrosion-resistant.',
    category: 'tanks',
    rating: 4.4,
    reviews: 15,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'top-tank-1500l',
    name: 'Top Tank 1500L',
    price: 4500.00,
    images: ['/top tank 1500L.png'],
    description: 'A compact 1500L Top Tank.',
    longDescription: 'A compact 1500L Top Tank, suitable for smaller households. Made with durable, high-quality plastic.',
    category: 'tanks',
    rating: 4.6,
    reviews: 28,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'top-tank-2000l',
    name: 'Tank 2000L',
    price: 5000.00,
    images: ['/top tank.png'],
    description: 'A standard 2000L Top Tank.',
    longDescription: 'A standard 2000L Top Tank offering great value and reliability for your water storage requirements.',
    category: 'tanks',
    rating: 4.7,
    reviews: 35,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'rainwater-tank',
    name: 'Rainwater Harvesting Tank',
    price: 8000.00,
    images: ['/rainwater-tank.png'],
    description: 'Tank designed for rainwater harvesting.',
    longDescription: 'An eco-friendly solution for water conservation. This tank is specifically designed for efficient rainwater harvesting.',
    category: 'tanks',
    rating: 4.8,
    reviews: 40,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
];

const decorProducts: Product[] = [
  {
    id: 'golden-chandelier',
    name: 'Golden Chandelier',
    price: 3500.00,
    images: ['/golden chandelier.png'],
    description: 'An elegant golden chandelier for a luxurious touch.',
    longDescription: 'An elegant golden chandelier for a luxurious touch. Perfect for dining rooms, living rooms, and grand entryways. Features high-quality crystals and a durable gold-finish frame.',
    category: 'decor',
    rating: 4.8,
    reviews: 22,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'rugged-chandelier',
    name: 'Rugged Chandelier',
    price: 5000.00,
    images: ['/rugged chandelier.png'],
    description: 'A stylish rugged chandelier with a modern design.',
    longDescription: 'A stylish rugged chandelier with a modern design. Its unique industrial look adds character to any space. Made with high-quality materials for longevity.',
    category: 'decor',
    rating: 4.7,
    reviews: 19,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'square-lights',
    name: 'Decorative Square Lights',
    price: 2800.00,
    images: ['/square lights.png'],
    description: 'Modern and sleek decorative square lights.',
    longDescription: 'Modern and sleek decorative square lights that provide a minimalist aesthetic. Energy-efficient LED technology ensures bright light with low power consumption.',
    category: 'decor',
    rating: 4.6,
    reviews: 31,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'birds-lights',
    name: 'Birds Lights',
    price: 1900.00,
    images: ['/birds lights.png'],
    description: 'Whimsical bird-shaped decorative lights.',
    longDescription: 'Add a touch of nature and whimsy to your room with these charming bird-shaped lights. Perfect for nurseries, bedrooms, or any space that needs a creative flair.',
    category: 'decor',
    rating: 4.9,
    reviews: 40,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'pinkish-sink',
    name: 'Pinkish Sink',
    price: 3000.00,
    images: ['/pinkish sink.png'],
    description: 'A chic and modern pinkish sink.',
    longDescription: 'Make a bold statement in your bathroom with this chic and modern pinkish sink. Made from high-quality ceramic, it is both durable and stylish.',
    category: 'decor',
    rating: 4.5,
    reviews: 15,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'bathroom-makeover-sink',
    name: 'Bathroom Makeover Sink',
    price: 7500.00,
    images: ['/Bathroom makeOver Sink.png'],
    description: 'Complete sink unit for a bathroom makeover.',
    longDescription: 'A complete sink and vanity unit to instantly upgrade your bathroom. Includes a modern basin, faucet, and storage cabinet. Easy to install.',
    category: 'decor',
    rating: 4.8,
    reviews: 25,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'monkey-lights',
    name: 'Monkey Lights',
    price: 4000.00,
    images: ['/monkey lights.png'],
    description: 'Playful and unique monkey-themed lights.',
    longDescription: 'Bring a sense of fun and adventure to your decor with these playful monkey-themed lights. A great conversation starter and a unique piece of functional art.',
    category: 'decor',
    rating: 4.7,
    reviews: 18,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'golden-stripe-chandelier',
    name: 'Golden Stripe Chandelier',
    price: 8000.00,
    images: ['/Golden stripe Chandelier.jpg'],
    description: 'A luxurious chandelier with golden stripes.',
    longDescription: 'This luxurious chandelier features a beautiful design with golden stripes, creating a stunning visual effect. It is the perfect centerpiece for a sophisticated room.',
    category: 'decor',
    rating: 4.9,
    reviews: 30,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
   {
    id: 'blackmate-golden-chandelier',
    name: 'BlackMate Golden Chandelier',
    price: 8500.00,
    images: ['/BlackMate golden Chandelier.jpg'],
    description: 'Elegant black matte and golden chandelier.',
    longDescription: 'Combining black matte and golden finishes, this chandelier offers a contemporary and elegant look. Its high-quality construction ensures it will be a lasting addition to your home.',
    category: 'decor',
    rating: 4.8,
    reviews: 28,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
   {
    id: 'wall-lights',
    name: 'Wall Lights',
    price: 2000.00,
    images: ['/Wall lights.jpg'],
    description: 'Stylish and modern wall lights for any room.',
    longDescription: 'These stylish and modern wall lights provide excellent ambient lighting and can complement a variety of decor styles. Energy-efficient and easy to install.',
    category: 'decor',
    rating: 4.6,
    reviews: 35,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
   {
    id: 'modern-soap-dish',
    name: 'Modern Soap Dish',
    price: 1500.00,
    images: ['/soap dish.png'],
    description: 'A sleek and modern soap dish for your bathroom.',
    longDescription: 'Keep your soap dry and your counter clean with this sleek and modern soap dish. Its minimalist design fits perfectly in any contemporary bathroom.',
    category: 'decor',
    rating: 4.5,
    reviews: 50,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
   {
    id: 'round-brown-frencia-countertop',
    name: 'Round Brown Frencia Countertop',
    price: 5500.00,
    images: ['/Round brown frencia countertop.jpg'],
    description: 'A beautiful round brown frencia countertop sink.',
    longDescription: 'This countertop sink features a beautiful round brown frencia design, adding a touch of rustic elegance to your bathroom. Made from durable, high-quality material.',
    category: 'decor',
    rating: 4.7,
    reviews: 21,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'golden-layers-chandelier',
    name: 'Golden Layers Chandelier',
    price: 4000.00,
    images: ['/golden layers.jpg'],
    description: 'A stunning chandelier with golden layers.',
    longDescription: 'This stunning chandelier features multiple golden layers that create a captivating light effect. A perfect statement piece for modern and classic interiors.',
    category: 'decor',
    rating: 4.8,
    reviews: 19,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'pink-oval-frencia-toilet',
    name: 'PinkOval Frencia Toilet',
    price: 8500.00,
    images: ['/PinkOval Frencia toilet.jpg'],
    description: 'A unique pink oval frencia toilet.',
    longDescription: 'Add a splash of color and unique style to your bathroom with this pink oval frencia toilet. Combines a distinctive look with modern, water-saving functionality.',
    category: 'decor',
    rating: 4.6,
    reviews: 12,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'designer-single-unit-toilet',
    name: 'Designer Single-Unit Toilet',
    price: 29500.00,
    images: ['/Designer singleUnit toilet.jpg'],
    description: 'A high-end designer single-unit toilet.',
    longDescription: 'Experience luxury with this high-end designer single-unit toilet. Its seamless design and premium features offer superior comfort and performance.',
    category: 'decor',
    rating: 5.0,
    reviews: 8,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'striped-chandelier',
    name: 'Striped Chandelier',
    price: 8000.00,
    images: ['/Striped Chandelier.jpg'],
    description: 'A modern chandelier with a striped design.',
    longDescription: 'This modern chandelier features a unique striped design that makes it a focal point in any room. Provides ample lighting while being a work of art.',
    category: 'decor',
    rating: 4.7,
    reviews: 14,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'decor-large-chandelier',
    name: 'Decor Large Chandelier',
    price: 14500.00,
    images: ['/Decor large Chandelier.jpg'],
    description: 'A large and impressive decorative chandelier.',
    longDescription: 'Make a grand statement with this large decorative chandelier. Its intricate design and impressive size are perfect for spaces with high ceilings.',
    category: 'decor',
    rating: 4.9,
    reviews: 20,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'classic-chandelier',
    name: 'Classic Chandelier',
    price: 2500.00,
    images: ['/classic chandelier.png'],
    description: 'A timeless and classic chandelier.',
    longDescription: 'This timeless chandelier brings classic elegance to any home. Its graceful design and warm light create a welcoming atmosphere.',
    category: 'decor',
    rating: 4.6,
    reviews: 45,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'stylish-mirror',
    name: 'Stylish Mirror',
    price: 2000.00,
    images: ['/Stylish mirror.jpg'],
    description: 'A stylish mirror to enhance your decor.',
    longDescription: 'Enhance your decor with this stylish mirror. Its modern frame and high-quality reflection make it a perfect addition to any room, from entryways to bathrooms.',
    category: 'decor',
    rating: 4.5,
    reviews: 33,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: '5-lamp-chandelier-general',
    name: '5-Lamp Chandelier General',
    price: 5100.00,
    images: ['/5 Lamp Chandelier General.png'],
    description: 'A general-purpose 5-lamp chandelier.',
    longDescription: 'A versatile 5-lamp chandelier that provides ample light and fits well in a variety of settings. A practical and stylish lighting solution.',
    category: 'decor',
    rating: 4.7,
    reviews: 28,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'hexagonal-decor-light',
    name: 'Hexagonal Decor Light',
    price: 3800.00,
    images: ['/hexagonal decor light.jpg'],
    description: 'A modern hexagonal decorative light fixture.',
    longDescription: 'This modern decorative light features a trendy hexagonal design. It can be used alone or grouped together to create a custom lighting installation.',
    category: 'decor',
    rating: 4.8,
    reviews: 15,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'round-smart-mirror',
    name: 'Round Smart Mirror',
    price: 4500.00,
    images: ['/Round smart mirror.jpg'],
    description: 'A round smart mirror with LED lighting.',
    longDescription: 'Upgrade your bathroom with this round smart mirror. It features integrated LED lighting with adjustable brightness and an anti-fog function.',
    category: 'decor',
    rating: 4.9,
    reviews: 25,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'stunning-mirror',
    name: 'Stunning Mirror',
    price: 1000.00,
    images: ['/Stunning mirror.jpg'],
    description: 'A stunning mirror with a unique frame.',
    longDescription: 'This stunning mirror features a unique and eye-catching frame that makes it a piece of wall art. Perfect for adding a decorative touch to any space.',
    category: 'decor',
    rating: 4.7,
    reviews: 30,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'ceiling-3mode-light',
    name: 'Ceiling 3-Mode Light',
    price: 6500.00,
    images: ['/Ceiling 3mode light.jpg'],
    description: 'A ceiling light with 3 different light modes.',
    longDescription: 'This versatile ceiling light offers three different light modes (e.g., warm, cool, and neutral) to suit any mood or occasion. Sleek, modern, and energy-efficient.',
    category: 'decor',
    rating: 4.8,
    reviews: 22,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'square-toilet',
    name: 'Square Toilet',
    price: 29000.00,
    images: ['/square toilet.jpg'],
    description: 'A modern, geometric square toilet.',
    longDescription: 'This toilet features a bold, geometric square design for a distinctly modern bathroom. Includes a soft-close seat and efficient dual-flush system.',
    category: 'decor',
    rating: 4.9,
    reviews: 10,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
  {
    id: 'designer-sink',
    name: 'Designer Sink',
    price: 3500.00,
    images: ['/Designer sink.jpg'],
    description: 'A designer sink with a unique shape.',
    longDescription: 'This designer sink stands out with its unique shape and high-quality finish. It serves as a functional sculpture for your bathroom countertop.',
    category: 'decor',
    rating: 4.7,
    reviews: 18,
    seller: { name: 'Alpha Electricals', id: 'seller-alpha' },
  },
];


const legacyProducts: Product[] = [
  {
    id: '1',
    name: 'Advanced Drone',
    description: 'High-performance drone with 4K camera and 30-min flight time.',
    longDescription: 'Capture stunning aerial footage with this professional-grade drone. Features include a 4K UHD camera, 3-axis gimbal stabilization, 30-minute flight time per battery, and intelligent flight modes like object tracking and waypoint navigation. Ideal for both hobbyists and professional photographers.',
    price: 799.99,
    images: ['https://placehold.co/600x600', 'https://placehold.co/600x600', 'https://placehold.co/600x600'],
    category: 'electronics',
    rating: 4.8,
    reviews: 125,
    seller: { name: 'TechFly Inc.', id: 'seller-1' },
  },
];

const allProducts = [...featuredProducts, ...tankProducts, ...decorProducts, ...legacyProducts];

const categories: Category[] = [
  { id: 'lighting-electrical', name: 'Lighting & Electrical' },
  { id: 'plumbing', name: 'Plumbing' },
  { id: 'decor', name: 'Home & Decor' },
  { id: 'roofing', name: 'Roofing & Fencing' },
  { id: 'tanks', name: 'Tanks' },
  { id: 'electronics', name: 'Electronics' },
];

export async function getHomePageCategories(): Promise<HomePageCategory[]> {
  await new Promise(resolve => setTimeout(resolve, 100));
  return homePageCategories;
}

export async function getFeaturedProducts(): Promise<Product[]> {
  await new Promise(resolve => setTimeout(resolve, 100));
  return featuredProducts;
}

export async function getProducts(): Promise<Product[]> {
  await new Promise(resolve => setTimeout(resolve, 500));
  return allProducts;
}

export async function getProductById(id: string): Promise<Product | undefined> {
  await new Promise(resolve => setTimeout(resolve, 200));
  return allProducts.find(p => p.id === id);
}

export async function getCategories(): Promise<Category[]> {
  await new Promise(resolve => setTimeout(resolve, 100));
  return categories;
}

export async function getTankProducts(): Promise<Product[]> {
  await new Promise(resolve => setTimeout(resolve, 100));
  return tankProducts;
}

export async function getDecorProducts(): Promise<Product[]> {
  await new Promise(resolve => setTimeout(resolve, 100));
  return allProducts.filter(p => p.category === 'decor');
}
